### ISSUE TITLE
Bug Report: App crashes when trying to change installation folder in settings

### ISSUE THREAD

**Issue by ArcadeArchie** [affederaffe/BeatSaberModManager#17]
**Describe the bug**
When clicking "Select folder" in the settings the app just crashes

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Select folder' under 'Installation'

**Expected behavior**
the app should open the folder select dialog after clicking "Select Folder"

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: 6.1.1-1-MANJARO
 - Version 0.0.4

**Additional context**
Error log:
`Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder' threw an exception.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable1)
   at Tmds.DBus.CodeGen.TypeExtensions.GetConstructor(Type, BindingFlags, Type[])
   at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder..cctor()
   --- End of inner exception stack trace ---
   at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder.Build(Type)
   at Tmds.DBus.CodeGen.DynamicAssembly.GetProxyTypeInfo(Type)
   at Tmds.DBus.Connection.CreateProxy(Type, String, ObjectPath)
   at Tmds.DBus.Connection.CreateProxy[T](String, ObjectPath)
   at Avalonia.FreeDesktop.DBusSystemDialog.<>c.<.cctor>b__15_0() in /_/src/Avalonia.FreeDesktop/DBusSystemDialog.cs:line 18
   at System.Lazy1.ViaFactory(LazyThreadSafetyMode)
   at System.Lazy1.ExecutionAndPublication(LazyHelper, Boolean)
   at System.Lazy1.CreateValue()
   at Avalonia.FreeDesktop.DBusSystemDialog.TryCreate(IPlatformHandle) in /_/src/Avalonia.FreeDesktop/DBusSystemDialog.cs:line 23
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.EnsureStorageProvider() in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 25
   at Avalonia.X11.NativeDialogs.CompositeStorageProvider.OpenFolderPickerAsync(FolderPickerOpenOptions) in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 49
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver1.OnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink1.ForwardOnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink2.OnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink1.ForwardOnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink2.OnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink1.ForwardOnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink2.OnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink1.ForwardOnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink2.OnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink1.ForwardOnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink2.OnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink1.ForwardOnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Sink2.OnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 94
   at System.Reactive.Sink1.ForwardOnError(Exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.SelectMany2.TaskSelector._.OnCompletedTask(Task1) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1559
   at System.Reactive.Linq.ObservableImpl.SelectMany2.TaskSelector._.OnNext(TSource) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1532
   at System.Reactive.AutoDetachObserver1.OnNextCore(T) in /_/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs:line 61
   at Avalonia.Interactivity.InteractiveExtensions.<>c__DisplayClass1_11.<GetObservable>b__1(Object , TEventArgs) in /_/src/Avalonia.Base/Interactivity/InteractiveExtensions.cs:line 56
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 118
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive, RoutedEventArgs) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 126
   at Avalonia.Controls.Button.OnClick() in /_/src/Avalonia.Controls/Button.cs:line 346
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs) in /_/src/Avalonia.Controls/Button.cs:line 418
   at System.Reactive.Subjects.Subject1.OnNext(T) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 118
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive, RoutedEventArgs) in /_/src/Avalonia.Base/Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs) in /_/src/Avalonia.Base/Interactivity/Interactive.cs:line 126
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement ) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 187
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs) in /_/src/Avalonia.Base/Input/MouseDevice.cs:line 55
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs) in /_/src/Avalonia.Base/Input/InputManager.cs:line 37
   at Avalonia.RawEventGrouper.DispatchFromQueue() in /_/src/Shared/RawEventGrouping.cs:line 59
   at Avalonia.Threading.JobRunner.RunJobs(Nullable1) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T, String[], ShutdownMode ) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at BeatSaberModManager.Startup.RunAvaloniaApp()
   at BeatSaberModManager.Startup.RunAsync()
   at BeatSaberModManager.Program.Container.global::StrongInject.IAsyncContainer<BeatSaberModManager.Startup>.RunAsync[TResult,TParam](Func3, TParam)
   at BeatSaberModManager.Program.Main(String[])
   at BeatSaberModManager.Program.Main(String[])
   at BeatSaberModManager.Program.<Main>(String[] )
zsh: IOT instruction (core dumped)  ./BeatSaberModManager
`

**Comment by affederaffe** [comment]
This is an issue with the UI framework (Avalonia), which I'm currently working on, see https://github.com/AvaloniaUI/Avalonia/pull/9810.

**Comment by affederaffe** [comment]
Since https://github.com/AvaloniaUI/Avalonia/pull/9810 is merged, the latest Actions build should work now.
