### ISSUE TITLE
App crashes on clicking "Install Playlist"

### ISSUE THREAD

**Issue by c-x-berger** [affederaffe/BeatSaberModManager#18]
When I attempt to install a playlist, Beat Saber Mod Manager crashes with the following exception:

```
Application crashed
System.TypelnitializationException: The type initializer for 'Tmds.DBus.CodeGen.DBusObjectProxy TypeBuilder' threw an exception.
→System.InvalidOperationException: Sequence contains no elements
at System.Linq.ThrowHelper.ThrowNoElementsException()
at System.Linq.Enumerable.Single [TSource] (IEnumerable`1)
at Tmds.DBus.CodeGen.TypeExtensions.GetConstructor(Type, BindingFlags, Type[])
at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder..cctor()
--- End of inner exception stack trace ---
at Tmds.DBus.CodeGen.DBusObjectProxyTypeBuilder.Build(Type) at Tmds.DBus.CodeGen.DynamicAssembly.GetProxyTypeInfo(Type)
at Tmds.DBus.Connection.CreateProxy(Type, String, ObjectPath)
at Tmds.DBus.Connection.CreateProxy[T](String, ObjectPath)
at Avalonia.FreeDesktop.DBusSystemDialog.<>c.<.cctor>b__15_0() in /_/src/Avalonia.FreeDesktop/DBusSystemDialog.cs:line 18 at System.Lazy`1.ViaFactory(LazyThreadSafetyMode)
at System.Lazy`1.ExecutionAndPublication (LazyHelper, Boolean)
at System.Lazy`1.CreateValue()
at Avalonia.FreeDesktop.DBusSystemDialog. TryCreate(IPlatformHandle) in /_/src/Avalonia.Free Desktop/DBusSystemDialog.cs:line 23 at Avalonia.X11.NativeDialogs.Composite Storage Provider.EnsureStorageProvider()
in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 25
at Avalonia.X11.NativeDialogs.Composite StorageProvider.OpenFilePickerAsync(FilePickerOpenOptions)
in /_/src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs:line 37
```
It looks like something's going wrong in trying to open a file picker?

I'm using KDE, if that helps debug things.

**Comment by affederaffe** [comment]
Same underlying issue as in #17.
