### ISSUE TITLE
Crash After Reinstalling mods

### ISSUE THREAD

**Issue by Da-Boom** [affederaffe/BeatSaberModManager#20]
Ok So i keep having this crash that seems to happen when i attempt to fully update or reinstall all or a subset of mods
BeatSaberModmanager Version: 0.0.5

```
Could not load library System.Net.Http.resources, Version=7.0.0.0, Culture=en-AU, PublicKeyToken=b03f5f7f11d50a3a
Could not load library System.Net.Http.resources, Version=7.0.0.0, Culture=en-AU, PublicKeyToken=b03f5f7f11d50a3a
Could not load library System.Net.Http.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
Could not load library System.Net.Http.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object , TEventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvent.cs:line 157
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_1.<.cctor>b__7(Object , PropertyChangedEventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvents.cs:line 29
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs) in /_/src/ReactiveUI/ReactiveObject/ReactiveObject.cs:line 96
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1379
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs:line 829
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 240
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
   at System.Reactive.Subjects.Subject`1.OnNext(T) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 397
   at ReactiveUI.IReactiveObjectExtensions.RaisingPropertyChanged[TSender](TSender, String) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 240
   at ReactiveUI.OAPHCreationHelperMixin.<>c__DisplayClass14_0`2.<ObservableToProperty>b__0(TRet) in /_/src/ReactiveUI/ObservableForProperty/OAPHCreationHelperMixin.cs:line 797
   at ReactiveUI.ObservableAsPropertyHelper`1.<>c__DisplayClass8_0.<.ctor>b__2(T) in /_/src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs:line 161
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 561
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 507
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler, ObserveOnObserverNew`1) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 497
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T, String[], ShutdownMode ) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at BeatSaberModManager.Startup.RunAvaloniaApp()
   at BeatSaberModManager.Startup.RunAsync()
   at BeatSaberModManager.Program.Container.global::StrongInject.IAsyncContainer<BeatSaberModManager.Startup>.RunAsync[TResult,TParam](Func`3, TParam)
   at BeatSaberModManager.Program.Main(String[])
   at BeatSaberModManager.Program.Main(String[])
   at BeatSaberModManager.Program.<Main>(String[] )
Aborted (core dumped)
```
I am running Linux with the current (as of  21 March 2023) version of beat saber
Nvidia Driver 5.0.30.02 (RTX 2070)
A HTC Vive HMD
Linux Kernel: 6.2.2-arch1-1 (I use Arch BTW)
XFCE 4.18
GTK 3.24.37

**Comment by Da-Boom** [comment]
I Seem to get slightly different behavior when steamVR is not running - either a dialog box before it crashes or no crash at all
