### ISSUE TITLE
Unable to Install Mods in v1.27.0

### ISSUE THREAD

**Issue by PoisonPhang** [affederaffe/BeatSaberModManager#7]
After updating both my game and the mod manager, I've been unable to install mods.

I made sure to remove all mods and launch the game before trying but this failed.

Let me know if you need any other details.

Logs below

```
-n,-f,--relativeToPwd,Beat Saber.exe
Restoring old version...
Copying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/System.RunCopying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/I18N.West.Copying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/IPA.LoaderCopying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/IPA.LoaderCopying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/Microsoft.Copying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/IPA.InjectCopying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/IPA.LoaderCopying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/IPA.InjectCopying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/Beat Saber_Data/Managed/netstandarCopying /mnt/games/SteamLibrary/steamapps/common/Beat Saber/winhttp.dll
Creating plugins folder...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Utilities.WeakEvent`2.Subscription.OnEvent(Object , TEventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvent.cs:line 162
   at Avalonia.Utilities.WeakEvents.<>c__DisplayClass5_1.<.cctor>b__7(Object , PropertyChangedEventArgs) in /_/src/Avalonia.Base/Utilities/WeakEvents.cs:line 29
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs) in /_/src/ReactiveUI/ReactiveObject/ReactiveObject.cs:line 96
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1379
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs:line 829
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 240
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
   at System.Reactive.Subjects.Subject`1.OnNext(T) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 141
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 397
   at ReactiveUI.IReactiveObjectExtensions.RaisingPropertyChanged[TSender](TSender, String) in /_/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs:line 240
   at ReactiveUI.OAPHCreationHelperMixin.<>c__DisplayClass14_0`2.<ObservableToProperty>b__0(TRet) in /_/src/ReactiveUI/ObservableForProperty/OAPHCreationHelperMixin.cs:line 797
   at ReactiveUI.ObservableAsPropertyHelper`1.<>c__DisplayClass8_0.<.ctor>b__2(T) in /_/src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs:line 161
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 561
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 507
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler, ObserveOnObserverNew`1) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 497
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T, String[], ShutdownMode ) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at BeatSaberModManager.Startup.RunAvaloniaApp()
   at BeatSaberModManager.Startup.RunAsync()
   at BeatSaberModManager.Program.Container.global::StrongInject.IAsyncContainer<BeatSaberModManager.Startup>.RunAsync[TResult,TParam](Func`3, TParam)
   at BeatSaberModManager.Program.Main(String[])
   at BeatSaberModManager.Program.Main(String[])
   at BeatSaberModManager.Program.<Main>(String[] )
[1]    152865 IOT instruction (core dumped)  ./.bin/BeatSaberModManager
```

**Comment by Atemu** [comment]
Also experiencing this on 0.0.4 using our packaged version in Nixpkgs.

**Comment by affederaffe** [comment]
Should be fixed with https://github.com/affederaffe/BeatSaberModManager/commit/f8d6e28bdaba05028d427aa102a3e616f0b2ed4b.

**Comment by PoisonPhang** [comment]
I can no longer test this myself, but will mark as closed as it seems to be fixed by recent changes
